# Generated by Django 3.2.9 on 2021-11-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0005_alter_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStock',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
