# Generated by Django 3.2.9 on 2021-11-30 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0014_auto_20211130_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copies',
            name='_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simple.product'),
        ),
    ]
