# Generated by Django 3.2.9 on 2021-12-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0017_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
