# Generated by Django 3.2.9 on 2021-12-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0020_auto_20211202_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copies',
            name='stockCp1',
        ),
    ]
