# Generated by Django 3.2.9 on 2021-12-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0022_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='createdAt',
        ),
    ]
