# Generated by Django 3.2.9 on 2021-12-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0023_remove_product_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='picture',
        ),
    ]
