# Generated by Django 3.2.9 on 2021-12-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0024_rename_image_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
