# Generated by Django 3.2.9 on 2021-11-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0004_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
