# Generated by Django 3.2.9 on 2021-11-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0006_auto_20211129_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
