# Generated by Django 3.2.9 on 2021-11-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0008_auto_20211130_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
