# Generated by Django 3.2.9 on 2021-11-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0009_alter_product_sku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Copies',
        ),
    ]
