# Generated by Django 3.2.9 on 2021-11-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0010_delete_copies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simple.product')),
            ],
        ),
    ]
