# Generated by Django 3.2.9 on 2021-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0013_auto_20211130_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
