# Generated by Django 3.2.9 on 2021-12-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0016_auto_20211202_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
