# Generated by Django 3.2.9 on 2021-12-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0019_copies_pcp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copies',
            name='pCp',
        ),
        migrations.AddField(
            model_name='copies',
            name='stockCp1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
