# Generated by Django 3.2.9 on 2021-12-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0021_remove_copies_stockcp1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
