# Generated by Django 3.2.9 on 2021-12-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0027_alter_copies_stockcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copies',
            name='stockCp',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
